language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

addons:
  sauce_connect:
    username: ikerin
    access_key:
      secure: "MKQ0mB+iA2cQR5uf3p/ckipDf9pQ67RK+XePYSKVbzAWZoaodKSvjnMPY6ZF8/vS/mogRVAwGwEm6D2b0xFZslWL8nmKRPhxZA8NSwT9FEPPwVgSCm9itDoBmpVwQu7XxEzGO58YsXwYxQe85VMhxkQw/V5107ocGe+oW92XFN4mmUugAvTC8TxZTB6o5YFOYn5HcWDKCBA9X26Oh3z1fv2AJmMTAXh5BVnq8IBeEoiBhaEA6TPWPDy7pwLTm8Tb20uamK35dbM3GWgkZtKW9fAldqdjPutCiz4DrZZhM6ZqIMLEfKhZtYY55FQwDrzugxvytFq2C+0K6IMDSM2Hvr12amVkXFii19N3B/0+8Rrr+uDBGkRWIOu+FcjpC7b3XYd+KvOBwRTZPx/Mr+gOlhu7p87sbF/RJ9gpCdo7hQPu//QaJM2pNzRvhgG3dNIexDJGyDnw2K4P5DJByOJCeVCec/nlNR2XIHOuAT9/tBn24AeBNECeE5ktYt1BExJNwd9hxNuThniMxy3v7Nsaxi+LHK58lSV1puCDuAd7/G+N12R4YTQ8UTRvZpZTBwdlxIz58MEHrRsYTWC3t0d5P5AAzuG2vDBarneU1KZe1I2LmtDcfHJxNl9OxuS4M5dRFDdVIEborx6WRDeHqrI1DHmYOX5G9rQyadcu/HcYbWQ="

cache:
  directories:
  - $HOME/.composer/cache

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
